-- creating "logs" table
CREATE TABLE IF NOT EXISTS logs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    service VARCHAR(255) NOT NULL,
    information_type VARCHAR(50) NOT NULL,
    event TEXT NOT NULL
);

-- creating "enviroment_data" table
CREATE TABLE IF NOT EXISTS environment_data (
    id SERIAL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    city VARCHAR(100) NOT NULL,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,

    -- Pogoda
    temperature NUMERIC(5,2),
    feelslike NUMERIC(5,2),
    humidity INT,
    wind_kph NUMERIC(5,2),
    precip_mm NUMERIC(5,2),
    cloud INT,
    visibility_km NUMERIC(5,2),
    uv_index NUMERIC(4,2),
    is_day VARCHAR(10),
    condition TEXT,

    -- Jakość powietrza
    pm2_5 NUMERIC(6,2),
    pm10 NUMERIC(6,2),
    co NUMERIC(8,2),
    no2 NUMERIC(6,2),
    o3 NUMERIC(6,2),
    so2 NUMERIC(6,2)
);

-- creating "bikes_cluster" table
CREATE TABLE IF NOT EXISTS bikes_cluster (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    station_id VARCHAR NOT NULL DEFAULT 'unknown',
    name VARCHAR NOT NULL DEFAULT 'unknown',
    capacity VARCHAR DEFAULT 'unknown',
    bikes_available VARCHAR DEFAULT 'unknown',
    docks_available VARCHAR DEFAULT 'unknown',
    manual_bikes_available VARCHAR DEFAULT 'unknown',
    electric_bikes_available VARCHAR DEFAULT 'unknown',
    temperature VARCHAR DEFAULT 'unknown',
    feelslike VARCHAR DEFAULT 'unknown',
    humidity VARCHAR DEFAULT 'unknown',
    wind_kph VARCHAR DEFAULT 'unknown',
    precip_mm VARCHAR DEFAULT 'unknown',
    cloud VARCHAR DEFAULT 'unknown',
    visibility_km VARCHAR DEFAULT 'unknown',
    uv_index VARCHAR DEFAULT 'unknown',
    daylight VARCHAR DEFAULT 'unknown',
    weather_condition VARCHAR DEFAULT 'unknown',
    fine_particles_pm2_5 VARCHAR DEFAULT 'unknown',
    coarse_particles_pm10 VARCHAR DEFAULT 'unknown',
    carbon_monoxide_ppb VARCHAR DEFAULT 'unknown',
    nitrogen_dioxide_ppb VARCHAR DEFAULT 'unknown',
    ozone_ppb VARCHAR DEFAULT 'unknown',
    sulfur_dioxide_ppb VARCHAR DEFAULT 'unknown'
);

-- creating "buses_cluster" table
CREATE TABLE IF NOT EXISTS buses_cluster (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    vehicle_id VARCHAR NOT NULL DEFAULT 'unknown',
    bus_line_number VARCHAR DEFAULT 'unknown',
    route_destination VARCHAR DEFAULT 'unknown',
    lat VARCHAR DEFAULT 'unknown',
    lon VARCHAR DEFAULT 'unknown',
    speed VARCHAR DEFAULT 'unknown',
    direction VARCHAR DEFAULT 'unknown',
    trip_identifier VARCHAR DEFAULT 'unknown',
    route_identifier VARCHAR DEFAULT 'unknown',
    stops_count VARCHAR DEFAULT 'unknown',
    average_delay_seconds VARCHAR DEFAULT 'unknown',
    maximum_delay_seconds VARCHAR DEFAULT 'unknown',
    minimum_delay_seconds VARCHAR DEFAULT 'unknown',
    delay_variance_value VARCHAR DEFAULT 'unknown',
    delay_standard_deviation VARCHAR DEFAULT 'unknown',
    delay_range_seconds VARCHAR DEFAULT 'unknown',
    stops_on_time_count VARCHAR DEFAULT 'unknown',
    stops_arrived_early_count VARCHAR DEFAULT 'unknown',
    stops_arrived_late_count VARCHAR DEFAULT 'unknown',
    delay_trend VARCHAR DEFAULT 'unknown',
    delay_consistency_score VARCHAR DEFAULT 'unknown',
    on_time_stop_ratio VARCHAR DEFAULT 'unknown',
    avg_positive_delay_seconds VARCHAR DEFAULT 'unknown',
    avg_negative_delay_seconds VARCHAR DEFAULT 'unknown',
    temperature VARCHAR DEFAULT 'unknown',
    feelslike VARCHAR DEFAULT 'unknown',
    humidity VARCHAR DEFAULT 'unknown',
    wind_kph VARCHAR DEFAULT 'unknown',
    precip_mm VARCHAR DEFAULT 'unknown',
    cloud VARCHAR DEFAULT 'unknown',
    visibility_km VARCHAR DEFAULT 'unknown',
    uv_index VARCHAR DEFAULT 'unknown',
    daylight VARCHAR DEFAULT 'unknown',
    weather_condition VARCHAR DEFAULT 'unknown',
    fine_particles_pm2_5 VARCHAR DEFAULT 'unknown',
    coarse_particles_pm10 VARCHAR DEFAULT 'unknown',
    carbon_monoxide_ppb VARCHAR DEFAULT 'unknown',
    nitrogen_dioxide_ppb VARCHAR DEFAULT 'unknown',
    ozone_ppb VARCHAR DEFAULT 'unknown',
    sulfur_dioxide_ppb VARCHAR DEFAULT 'unknown'
);

-- creating "bikes_class" table
CREATE TABLE IF NOT EXISTS bikes_class (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    station_id VARCHAR NOT NULL DEFAULT 'unknown',
    name VARCHAR NOT NULL DEFAULT 'unknown',
    capacity VARCHAR DEFAULT 'unknown',
    bikes_available VARCHAR DEFAULT 'unknown',
    docks_available VARCHAR DEFAULT 'unknown',
    manual_bikes_available VARCHAR DEFAULT 'unknown',
    electric_bikes_available VARCHAR DEFAULT 'unknown',
    temperature VARCHAR DEFAULT 'unknown',
    feelslike VARCHAR DEFAULT 'unknown',
    humidity VARCHAR DEFAULT 'unknown',
    wind_kph VARCHAR DEFAULT 'unknown',
    precip_mm VARCHAR DEFAULT 'unknown',
    cloud VARCHAR DEFAULT 'unknown',
    visibility_km VARCHAR DEFAULT 'unknown',
    uv_index VARCHAR DEFAULT 'unknown',
    daylight VARCHAR DEFAULT 'unknown',
    weather_condition VARCHAR DEFAULT 'unknown',
    fine_particles_pm2_5 VARCHAR DEFAULT 'unknown',
    coarse_particles_pm10 VARCHAR DEFAULT 'unknown',
    carbon_monoxide_ppb VARCHAR DEFAULT 'unknown',
    nitrogen_dioxide_ppb VARCHAR DEFAULT 'unknown',
    ozone_ppb VARCHAR DEFAULT 'unknown',
    sulfur_dioxide_ppb VARCHAR DEFAULT 'unknown',
    cluster_id VARCHAR DEFAULT 'unknown',
    cluster_prediction_success VARCHAR DEFAULT 'unknown'
);

-- creating "buses_class" table
CREATE TABLE IF NOT EXISTS buses_class (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    vehicle_id VARCHAR NOT NULL DEFAULT 'unknown',
    bus_line_number VARCHAR DEFAULT 'unknown',
    route_destination VARCHAR DEFAULT 'unknown',
    lat VARCHAR DEFAULT 'unknown',
    lon VARCHAR DEFAULT 'unknown',
    speed VARCHAR DEFAULT 'unknown',
    direction VARCHAR DEFAULT 'unknown',
    trip_identifier VARCHAR DEFAULT 'unknown',
    route_identifier VARCHAR DEFAULT 'unknown',
    stops_count VARCHAR DEFAULT 'unknown',
    average_delay_seconds VARCHAR DEFAULT 'unknown',
    maximum_delay_seconds VARCHAR DEFAULT 'unknown',
    minimum_delay_seconds VARCHAR DEFAULT 'unknown',
    delay_variance_value VARCHAR DEFAULT 'unknown',
    delay_standard_deviation VARCHAR DEFAULT 'unknown',
    delay_range_seconds VARCHAR DEFAULT 'unknown',
    stops_on_time_count VARCHAR DEFAULT 'unknown',
    stops_arrived_early_count VARCHAR DEFAULT 'unknown',
    stops_arrived_late_count VARCHAR DEFAULT 'unknown',
    delay_trend VARCHAR DEFAULT 'unknown',
    delay_consistency_score VARCHAR DEFAULT 'unknown',
    on_time_stop_ratio VARCHAR DEFAULT 'unknown',
    avg_positive_delay_seconds VARCHAR DEFAULT 'unknown',
    avg_negative_delay_seconds VARCHAR DEFAULT 'unknown',
    temperature VARCHAR DEFAULT 'unknown',
    feelslike VARCHAR DEFAULT 'unknown',
    humidity VARCHAR DEFAULT 'unknown',
    wind_kph VARCHAR DEFAULT 'unknown',
    precip_mm VARCHAR DEFAULT 'unknown',
    cloud VARCHAR DEFAULT 'unknown',
    visibility_km VARCHAR DEFAULT 'unknown',
    uv_index VARCHAR DEFAULT 'unknown',
    daylight VARCHAR DEFAULT 'unknown',
    weather_condition VARCHAR DEFAULT 'unknown',
    fine_particles_pm2_5 VARCHAR DEFAULT 'unknown',
    coarse_particles_pm10 VARCHAR DEFAULT 'unknown',
    carbon_monoxide_ppb VARCHAR DEFAULT 'unknown',
    nitrogen_dioxide_ppb VARCHAR DEFAULT 'unknown',
    ozone_ppb VARCHAR DEFAULT 'unknown',
    sulfur_dioxide_ppb VARCHAR DEFAULT 'unknown',
    cluster_id VARCHAR DEFAULT 'unknown',
    cluster_prediction_success VARCHAR DEFAULT 'unknown'
);
