from datetime import datetime, timedelta, timezone
from sqlalchemy import Column, Integer, String, TIMESTAMP, Double, Numeric, Text
from sqlalchemy.orm import declarative_base

Base = declarative_base()
CEST = timezone(timedelta(hours=2))

class LogsEntry(Base):
    __tablename__ = "logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    created_at = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    service = Column(String, unique=True, nullable=False)
    information_type = Column(String, nullable=False)
    event = Column(String, nullable=False)

class EnvironmentEntry(Base):
    __tablename__ = "environment_data"

    id = Column(Integer, primary_key=True, autoincrement=True)
    type = Column(String, nullable=False)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    city = Column(String, nullable=False)
    lat = Column(Double)
    lon = Column(Double)
    temperature = Column(Numeric)
    feelslike = Column(Numeric)
    humidity = Column(Integer)
    wind_kph = Column(Numeric)
    precip_mm = Column(Numeric)
    cloud = Column(Integer)
    visibility_km = Column(Numeric)
    uv_index = Column(Numeric)
    is_day = Column(String)
    condition = Column(Text)
    pm2_5 = Column(Numeric)
    pm10 = Column(Numeric)
    co = Column(Numeric)
    no2 = Column(Numeric)
    o3 = Column(Numeric)
    so2 = Column(Numeric)

class BikeCluster(Base):
    __tablename__ = 'bikes_cluster'

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    station_id = Column(String, nullable=False, default="unknown")
    name = Column(String, nullable=False, default="unknown")
    capacity = Column(String, default="unknown")
    bikes_available = Column(String, default="unknown")
    docks_available = Column(String, default="unknown")
    manual_bikes_available = Column(String, default="unknown")
    electric_bikes_available = Column(String, default="unknown")
    temperature = Column(String, default="unknown")
    feelslike = Column(String, default="unknown")
    humidity = Column(String, default="unknown")
    wind_kph = Column(String, default="unknown")
    precip_mm = Column(String, default="unknown")
    cloud = Column(String, default="unknown")
    visibility_km = Column(String, default="unknown")
    uv_index = Column(String, default="unknown")
    daylight = Column(String, default="unknown")
    weather_condition = Column(String, default="unknown")
    fine_particles_pm2_5 = Column(String, default="unknown")
    coarse_particles_pm10 = Column(String, default="unknown")
    carbon_monoxide_ppb = Column(String, default="unknown")
    nitrogen_dioxide_ppb = Column(String, default="unknown")
    ozone_ppb = Column(String, default="unknown")
    sulfur_dioxide_ppb = Column(String, default="unknown")

class BusesCluster(Base):
    __tablename__ = 'buses_cluster'

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    vehicle_id = Column(String, nullable=False, default="unknown")
    bus_line_number = Column(String, default="unknown")
    route_destination = Column(String, default="unknown")
    lat = Column(String, default="unknown")
    lon = Column(String, default="unknown")
    speed = Column(String, default="unknown")
    direction = Column(String, default="unknown")
    trip_identifier = Column(String, default="unknown")
    route_identifier = Column(String, default="unknown")
    stops_count = Column(String, default="unknown")
    average_delay_seconds = Column(String, default="unknown")
    maximum_delay_seconds = Column(String, default="unknown")
    minimum_delay_seconds = Column(String, default="unknown")
    delay_variance_value = Column(String, default="unknown")
    delay_standard_deviation = Column(String, default="unknown")
    delay_range_seconds = Column(String, default="unknown")
    stops_on_time_count = Column(String, default="unknown")
    stops_arrived_early_count = Column(String, default="unknown")
    stops_arrived_late_count = Column(String, default="unknown")
    delay_trend = Column(String, default="unknown")
    delay_consistency_score = Column(String, default="unknown")
    on_time_stop_ratio = Column(String, default="unknown")
    avg_positive_delay_seconds = Column(String, default="unknown")
    avg_negative_delay_seconds = Column(String, default="unknown")
    temperature = Column(String, default="unknown")
    feelslike = Column(String, default="unknown")
    humidity = Column(String, default="unknown")
    wind_kph = Column(String, default="unknown")
    precip_mm = Column(String, default="unknown")
    cloud = Column(String, default="unknown")
    visibility_km = Column(String, default="unknown")
    uv_index = Column(String, default="unknown")
    daylight = Column(String, default="unknown")
    weather_condition = Column(String, default="unknown")
    fine_particles_pm2_5 = Column(String, default="unknown")
    coarse_particles_pm10 = Column(String, default="unknown")
    carbon_monoxide_ppb = Column(String, default="unknown")
    nitrogen_dioxide_ppb = Column(String, default="unknown")
    ozone_ppb = Column(String, default="unknown")
    sulfur_dioxide_ppb = Column(String, default="unknown")

class BikeClass(Base):
    __tablename__ = 'bikes_class'

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    station_id = Column(String, nullable=False, default="unknown")
    name = Column(String, nullable=False, default="unknown")
    capacity = Column(String, default="unknown")
    bikes_available = Column(String, default="unknown")
    docks_available = Column(String, default="unknown")
    manual_bikes_available = Column(String, default="unknown")
    electric_bikes_available = Column(String, default="unknown")
    temperature = Column(String, default="unknown")
    feelslike = Column(String, default="unknown")
    humidity = Column(String, default="unknown")
    wind_kph = Column(String, default="unknown")
    precip_mm = Column(String, default="unknown")
    cloud = Column(String, default="unknown")
    visibility_km = Column(String, default="unknown")
    uv_index = Column(String, default="unknown")
    daylight = Column(String, default="unknown")
    weather_condition = Column(String, default="unknown")
    fine_particles_pm2_5 = Column(String, default="unknown")
    coarse_particles_pm10 = Column(String, default="unknown")
    carbon_monoxide_ppb = Column(String, default="unknown")
    nitrogen_dioxide_ppb = Column(String, default="unknown")
    ozone_ppb = Column(String, default="unknown")
    sulfur_dioxide_ppb = Column(String, default="unknown")
    cluster_id = Column(String, default="unknown")
    cluster_prediction_success = Column(String, default="unknown")

class BusesClass(Base):
    __tablename__ = 'buses_class'

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(TIMESTAMP(timezone=True), nullable=False, default=lambda: datetime.now(CEST))
    vehicle_id = Column(String, nullable=False, default="unknown")
    bus_line_number = Column(String, default="unknown")
    route_destination = Column(String, default="unknown")
    lat = Column(String, default="unknown")
    lon = Column(String, default="unknown")
    speed = Column(String, default="unknown")
    direction = Column(String, default="unknown")
    trip_identifier = Column(String, default="unknown")
    route_identifier = Column(String, default="unknown")
    stops_count = Column(String, default="unknown")
    average_delay_seconds = Column(String, default="unknown")
    maximum_delay_seconds = Column(String, default="unknown")
    minimum_delay_seconds = Column(String, default="unknown")
    delay_variance_value = Column(String, default="unknown")
    delay_standard_deviation = Column(String, default="unknown")
    delay_range_seconds = Column(String, default="unknown")
    stops_on_time_count = Column(String, default="unknown")
    stops_arrived_early_count = Column(String, default="unknown")
    stops_arrived_late_count = Column(String, default="unknown")
    delay_trend = Column(String, default="unknown")
    delay_consistency_score = Column(String, default="unknown")
    on_time_stop_ratio = Column(String, default="unknown")
    avg_positive_delay_seconds = Column(String, default="unknown")
    avg_negative_delay_seconds = Column(String, default="unknown")
    temperature = Column(String, default="unknown")
    feelslike = Column(String, default="unknown")
    humidity = Column(String, default="unknown")
    wind_kph = Column(String, default="unknown")
    precip_mm = Column(String, default="unknown")
    cloud = Column(String, default="unknown")
    visibility_km = Column(String, default="unknown")
    uv_index = Column(String, default="unknown")
    daylight = Column(String, default="unknown")
    weather_condition = Column(String, default="unknown")
    fine_particles_pm2_5 = Column(String, default="unknown")
    coarse_particles_pm10 = Column(String, default="unknown")
    carbon_monoxide_ppb = Column(String, default="unknown")
    nitrogen_dioxide_ppb = Column(String, default="unknown")
    ozone_ppb = Column(String, default="unknown")
    sulfur_dioxide_ppb = Column(String, default="unknown")
    cluster_id = Column(String, default="unknown")
    cluster_prediction_success = Column(String, default="unknown")
    